#!/bin/bash

for i in {1..100}
do 
  cp path_extraction_step3.slurm path_extraction_step3_tmp.slurm
  sed -i 's/partno/'$i'/g' path_extraction_step3_tmp.slurm

  sbatch path_extraction_step3_tmp.slurm
done

