#!/bin/bash

for i in {1..100}
do 
  cp path_extraction_step4_special_treatment_149.slurm path_extraction_step4_tmp.slurm
  sed -i 's/partno/'$i'/g' path_extraction_step4_tmp.slurm

  sbatch path_extraction_step4_tmp.slurm
done

