name: odinsynth
channels:
  - defaults
  - conda-forge
  - pytorch
  - huggingface
dependencies:
  - python=3.9
  - cudatoolkit=11.3.1
  - pytorch
  - transformers
  - pytorch-lightning=1.1.3
  - fastapi
  - uvicorn
  - scikit-learn
